name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: cd client && npm install  # ci instead of ci if no lock
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: android-actions/setup-android@v3
    - run: cd client/android && chmod +x gradlew
    - run: cd client && ./android/gradlew assembleDebug --stacktrace
    - uses: actions/upload-artifact@v4
      with:
        name: alix-apk
        path: client/android/app/build/outputs/apk/debug/app-debug.apk
